const booksIndex = {
  a: '/Index/a.json',
  b: '/Index/b.json',
  c: '/Index/c.json',
  d: '/Index/d.json',
  e: '/Index/e.json',
  f: '/Index/f.json',
  g: '/Index/g.json',
  h: '/Index/h.json',
  i: '/Index/i.json',
  j: '/Index/j.json',
  k: '/Index/k.json',
  l: '/Index/l.json',
  m: '/Index/m.json',
  n: '/Index/n.json',
  o: '/Index/o.json',
  p: '/Index/p.json',
  q: '/Index/q.json',
  r: '/Index/r.json',
  s: '/Index/s.json',
  t: '/Index/t.json',
  u: '/Index/u.json',
  v: '/Index/v.json',
  w: '/Index/w.json',
  x: '/Index/x.json',
  y: '/Index/y.json',
  z: '/Index/z.json',
}
